apiVersion: v1
kind: Service
metadata:
  name: biblers
  labels:
    app: app
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: biblers
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: biblers
        image: docker.pkg.github.com/dspeckhals/bible.rs:latest
        env:
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: sentry
                key: dsn
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: githubregcred
