name: Deploy

on:
  push:
    tags:
      - "*"

jobs:

  build_deploy:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          repository: dspeckhals/bible.rs/bible.rs
          registry: docker.pkg.github.com
          tag_with_ref: true
          tags: latest,${{ github.sha }}

      - name: Set kubectl Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Create Docker Repository Secret
        uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: docker.pkg.github.com
          container-registry-username: ${{ github.actor }}
          container-registry-password: ${{ github.token }}
          secret-name: githubregcred

      - name: Create Sentry Secret
        uses: azure/k8s-create-secret@v1
        with:
          secret-type: 'generic'
          arguments:  --from-literal=dsn=${{ secrets.SENTRY_DSN }}
          secret-name: sentry

      - name: Deploy to Cluster
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
              config/k8s/biblers.yml
              config/k8s/web.yml
          images: 'docker.pkg.github.com/dspeckhals/bible.rs:${{ github.sha }}'
          imagepullsecrets: githubregcred

