[package]
name = "web"
version = "0.1.0"
authors = ["Dustin Speckhals <dustin1114@gmail.com>"]
edition = "2018"

[dependencies.db]
path = "../db"

[dependencies]
actix-files = "0.3.0"
actix-web = "3.0.2"

dotenv = "0.15.0"
env_logger = "0.7.1"
handlebars = { version = "3.4.0", features = ["dir_source"] }
lazy_static = "1.4.0"
log = "0.4.11"
num_cpus = "1.13.0"
sentry = "0.20.1"
serde = "1.0.115"
serde_derive = "1.0.115"
serde_json = "1.0.57"
thiserror = "1.0.20"
url = "2.1.1"
